name: backbone
description: A Dart framework for writing REST APIs from an Open API spec.
version: 0.0.1-dev.10
repository: https://github.com/mtwichel/backbone

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  collection: ^1.15.0
  equatable: ^2.0.3
  http_parser: ^4.0.0
  json_annotation: ^4.4.0
  mason: ^0.0.1-dev.57
  open_api_forked: ^3.0.0+5
  process_run: ^0.12.2+2
  recase: ^4.0.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  stack_trace: ^1.10.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.5
  build_version: ^2.0.0
  coverage: ^1.0.3
  json_serializable: ^6.1.1
  mocktail: ^0.2.0
  test: ^1.20.0
  very_good_analysis: ^2.4.0

executables:
  backbone:
