name: {{#snakeCase}}{{apiName}}{{/snakeCase}}
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  {{#snakeCase}}{{apiName}}{{/snakeCase}}_functions_objects:
    path: ../../functions_objects