name: pets_api_functions_objects

version: 0.0.1
publish_to: none

environment: 
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_runner: ^2.1.5
  equatable: ^2.0.3
  json_annotation: ^4.4.0

dev_dependencies:
  json_serializable: ^6.1.1
