include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - bricks/**
    - example/**
    - "**/*_generator_bundle.dart"
linter:
  rules:
    public_member_api_docs: false
    avoid_print: false
